[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default.model_checker]
contracts = { "src/SpaceInvadersGame.sol" = [ "SpaceInvadersGame" ] }
engine = "chc"
timeout = 10000
targets = [ "assert" ]

[rpc_endpoints]
celo-sepolia = "https://forno.celo-sepolia.celo-testnet.org/"
celo = "https://forno.celo.org"
